const CATS={tv:{name:'مسلسلات',emoji:'📺',color:'#8168d8'},movies:{name:'أفلام',emoji:'🎬',color:'#ff7e6b'},songs:{name:'أغاني',emoji:'🎵',color:'#ef77ac'},artists:{name:'فنانين',emoji:'🎤',color:'#f4a340'},cartoons:{name:'كرتون وطفولة',emoji:'🧸',color:'#63b6e8'},sports:{name:'رياضة',emoji:'⚽',color:'#56b881'},general:{name:'معلومات عامة',emoji:'🌍',color:'#6375d6'}};
const TEAM_COLORS=['#6375d6','#ef77ac','#56b881','#f4a340','#8168d8','#ff7e6b'];
const app=document.getElementById('app');
let state={screen:'home',teamCount:2,rounds:7,teams:[],categories:Object.keys(CATS),currentTeam:0,currentRound:1,usedQuestions:new Set(),selectedCategory:null,currentQuestion:null,deadline:null,timerId:null};
function initialTeam(i){return{name:`الفريق ${i+1}`,score:0,color:TEAM_COLORS[i],lifelines:{hint:true,fifty:true,time:true,change:true}}}
function resetTeams(){state.teams=Array.from({length:state.teamCount},(_,i)=>initialTeam(i))}
function shell(content){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">لفّ<span>ها</span></div><div class="muted">Game Night عربي</div></div>${content}</div>`}
function render(){clearInterval(state.timerId);({home,setup,spin,difficulty,question,result,final:finalScreen}[state.screen]||home)()}
function home(){shell(`<section class="hero"><div class="hero-inner"><div class="eyebrow">GAME NIGHT</div><h1>لفّها، اختاروا التحدي<br>واجمعوا أكثر نقاط</h1><p class="hero-copy">كل فريق عنده <strong>دقيقة واحدة</strong> للإجابة. إذا انتهى الوقت أو كانت الإجابة غلط، يروح السؤال وتنتهي الفرصة — <strong>بدون تمرير للفريق الثاني.</strong></p><div class="how-row"><span>🎡 الفئة عشوائية</span><span>🎯 اختار 200 / 400 / 600</span><span>⏱️ 60 ثانية</span></div><button class="btn btn-primary btn-lg" id="start">ابدأ اللعبة</button></div></section>`);document.getElementById('start').onclick=()=>{state.screen='setup';render()}}
function setup(){if(!state.teams.length)resetTeams();shell(`<div class="card setup-card"><div class="setup-heading"><span>جاهزين؟</span><h1>جهزوا الفرق وابدؤوا</h1></div><div class="field"><h3 class="section-title">عدد الفرق</h3><div class="choice-row">${[2,3,4,5,6].map(n=>`<button class="choice ${state.teamCount===n?'active':''}" data-teamcount="${n}">${n}</button>`).join('')}</div></div><div class="field"><h3 class="section-title">أسماء الفرق</h3><div class="team-inputs">${state.teams.map((t,i)=>`<label class="team-input"><span class="team-dot" style="background:${t.color}"></span><input value="${t.name}" data-team="${i}" /></label>`).join('')}</div></div><div class="field"><h3 class="section-title">عدد الجولات</h3><div class="choice-row">${[5,7,10].map(n=>`<button class="choice ${state.rounds===n?'active':''}" data-rounds="${n}">${n} جولات</button>`).join('')}</div></div><div class="field"><h3 class="section-title">الفئات الموجودة في اللعبة</h3><p class="field-note">كل الفئات تدخل تلقائيًا في السحب.</p><div class="categories readonly">${Object.entries(CATS).map(([k,c])=>`<div class="cat-chip"><span class="emoji">${c.emoji}</span>${c.name}</div>`).join('')}</div></div><button class="btn btn-primary btn-lg" id="begin">ابدأ اللعبة</button></div>`);
document.querySelectorAll('[data-teamcount]').forEach(b=>b.onclick=()=>{state.teamCount=+b.dataset.teamcount;resetTeams();render()});document.querySelectorAll('[data-rounds]').forEach(b=>b.onclick=()=>{state.rounds=+b.dataset.rounds;render()});document.querySelectorAll('[data-team]').forEach(inp=>inp.oninput=()=>state.teams[+inp.dataset.team].name=inp.value||`الفريق ${+inp.dataset.team+1}`);document.getElementById('begin').onclick=()=>{state.currentTeam=0;state.currentRound=1;state.usedQuestions=new Set();state.categories=Object.keys(CATS);state.teams.forEach(t=>{t.score=0;t.lifelines={hint:true,fifty:true,time:true,change:true}});state.screen='spin';render()}}
function scoreboard(){return `<aside class="card score-card"><div class="score-head"><strong>النتيجة</strong><span class="round-badge">الجولة ${state.currentRound}/${state.rounds}</span></div><div class="score-list">${state.teams.map((t,i)=>`<div class="score-team ${i===state.currentTeam?'current':''}"><div class="team-meta"><span class="team-dot" style="background:${t.color}"></span><span>${t.name}</span></div><span class="score-num">${t.score}</span></div>`).join('')}</div><div class="lifeline-mini">${Object.entries(state.teams[state.currentTeam].lifelines).map(([k,v])=>`<span class="life-dot ${v?'':'used'}">${{hint:'💡',fifty:'✂️',time:'⏱️',change:'🔄'}[k]}</span>`).join('')}</div></aside>`}
function gameLayout(main){shell(`<div class="game-grid">${scoreboard()}<main class="card play-card">${main}</main></div>`)}
function spin(){const cats=state.categories.map(k=>CATS[k]);const stops=cats.map((c,i)=>`${c.color} ${i*360/cats.length}deg ${(i+1)*360/cats.length}deg`).join(',');gameLayout(`<div class="turn-label">الدور الآن</div><div class="turn-name">${state.teams[state.currentTeam].name}</div><div class="wheel-wrap"><div class="pointer"></div><div class="wheel" id="wheel" style="background:conic-gradient(${stops})">${cats.map((c,i)=>`<div class="wheel-label" style="transform:rotate(${i*360/cats.length+360/cats.length/2}deg) translate(150px) rotate(90deg)">${c.emoji} ${c.name}</div>`).join('')}<div class="wheel-center"><button id="spinBtn">لف</button></div></div></div>`);document.getElementById('spinBtn').onclick=()=>{const idx=Math.floor(Math.random()*state.categories.length);state.selectedCategory=state.categories[idx];const seg=360/state.categories.length;const target=1440+(360-(idx*seg+seg/2));document.getElementById('wheel').style.transform=`rotate(${target}deg)`;document.getElementById('spinBtn').disabled=true;setTimeout(()=>{state.screen='difficulty';render()},4100)}}
function difficulty(){const c=CATS[state.selectedCategory];gameLayout(`<div class="selected-cat">${c.emoji} ${c.name}</div><h2 class="center-title">كم نقطة تبون تخاطرون عليها؟</h2><div class="difficulty-grid"><button class="difficulty easy" data-diff="easy"><div class="points">200</div><small>أسهل</small></button><button class="difficulty medium" data-diff="medium"><div class="points">400</div><small>أدق</small></button><button class="difficulty hard" data-diff="hard"><div class="points">600</div><small>للي يعرف</small></button></div>`);document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>pickQuestion(b.dataset.diff))}
function pickQuestion(diff,excludeCurrent=false){let pool=QUESTIONS.filter(q=>q.category===state.selectedCategory&&q.difficulty===diff&&!state.usedQuestions.has(q.questionID));if(excludeCurrent&&state.currentQuestion)pool=pool.filter(q=>q.questionID!==state.currentQuestion.questionID);if(!pool.length)pool=QUESTIONS.filter(q=>q.category===state.selectedCategory&&q.difficulty===diff&&(!excludeCurrent||q.questionID!==state.currentQuestion?.questionID));if(!pool.length){toast('ما فيه سؤال متاح بهذا المستوى الآن');return}state.currentQuestion=pool[Math.floor(Math.random()*pool.length)];state.usedQuestions.add(state.currentQuestion.questionID);state.deadline=Date.now()+60000;state.screen='question';render()}
function shuffledAnswers(q){return [...(q.wrongAnswers||[]),q.correctAnswer].sort(()=>Math.random()-.5)}
function question(){const q=state.currentQuestion,c=CATS[q.category],team=state.teams[state.currentTeam],isMCQ=q.questionType==='mcq',answers=isMCQ?shuffledAnswers(q):[];let body='';if(q.questionType==='ordering'){body=`<div class="ordering-instruction">رتّبوا العناصر من <strong>${q.orderLabel||'الأكثر إلى الأقل'}</strong></div><div class="ordering-list">${q.items.map((x,i)=>`<div><span>${i+1}</span>${x}</div>`).join('')}</div><div class="direct-actions"><button class="btn correct-btn" id="correct">✓ الترتيب صحيح</button><button class="btn wrong-btn" id="wrong">✕ الترتيب خطأ</button></div>`}else if(q.questionType==='logo'){body=`<div class="logo-question"><div class="logo-mark">${q.logoText||'?'}</div><div class="logo-sub">${q.logoSub||''}</div></div><div class="answers">${answers.map(a=>`<button class="answer-btn" data-answer="${a.replace(/"/g,'&quot;')}">${a}</button>`).join('')}</div>`}else if(isMCQ){body=`<div class="answers">${answers.map(a=>`<button class="answer-btn" data-answer="${a.replace(/"/g,'&quot;')}">${a}</button>`).join('')}</div>`}else{body=`<div class="direct-actions"><button class="btn correct-btn" id="correct">✓ إجابة صحيحة</button><button class="btn wrong-btn" id="wrong">✕ إجابة خاطئة</button></div>`}
gameLayout(`<div class="question-shell"><div class="question-top"><div class="q-meta">${c.emoji} ${c.name} • ${q.points} نقطة</div><div class="timer" id="timer"><strong id="timeText">60</strong></div></div><div class="question-card"><div id="hintBox"></div><div class="question-text">${q.questionText}</div>${body}<div class="lifelines"><button class="life-btn" data-life="hint" ${team.lifelines.hint?'':'disabled'}>💡 تلميح</button><button class="life-btn" data-life="fifty" ${team.lifelines.fifty&&(isMCQ||q.questionType==='logo')?'':'disabled'}>✂️ 50/50</button><button class="life-btn" data-life="time" ${team.lifelines.time?'':'disabled'}>⏱️ +15</button><button class="life-btn" data-life="change" ${team.lifelines.change?'':'disabled'}>🔄 غير السؤال</button></div></div></div>`);
if(isMCQ||q.questionType==='logo')document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>finishQuestion(b.dataset.answer===q.correctAnswer?'correct':'wrong'));else{document.getElementById('correct').onclick=()=>finishQuestion('correct');document.getElementById('wrong').onclick=()=>finishQuestion('wrong')};document.querySelectorAll('[data-life]').forEach(b=>b.onclick=()=>useLife(b.dataset.life));tick();state.timerId=setInterval(tick,200)}
function tick(){const remaining=Math.max(0,state.deadline-Date.now()),sec=Math.ceil(remaining/1000),txt=document.getElementById('timeText'),timer=document.getElementById('timer');if(txt)txt.textContent=sec;if(timer)timer.style.setProperty('--progress',`${remaining/60000*100}%`);if(remaining<=0){clearInterval(state.timerId);finishQuestion('timeout')}}
function useLife(type){const team=state.teams[state.currentTeam],q=state.currentQuestion;if(!team.lifelines[type])return;if(type==='hint'){team.lifelines.hint=false;document.getElementById('hintBox').innerHTML=`<div class="hint-box">💡 ${q.hint||'ركزوا على التفاصيل.'}</div>`}if(type==='time'){team.lifelines.time=false;state.deadline+=15000;toast('تمت إضافة 15 ثانية')}if(type==='change'){team.lifelines.change=false;pickQuestion(q.difficulty,true);return}if(type==='fifty'&&(q.questionType==='mcq'||q.questionType==='logo')){team.lifelines.fifty=false;[...document.querySelectorAll('[data-answer]')].filter(b=>b.dataset.answer!==q.correctAnswer).sort(()=>Math.random()-.5).slice(0,2).forEach(b=>b.classList.add('hidden-answer'))}renderLifelineState()}
function renderLifelineState(){const team=state.teams[state.currentTeam];document.querySelectorAll('[data-life]').forEach(b=>{const t=b.dataset.life;b.disabled=!team.lifelines[t]||(t==='fifty'&&!['mcq','logo'].includes(state.currentQuestion.questionType))})}
function finishQuestion(status){clearInterval(state.timerId);if(state.screen!=='question')return;if(status==='correct')state.teams[state.currentTeam].score+=state.currentQuestion.points;state.lastResult=status;state.screen='result';render()}
function result(){const q=state.currentQuestion,ok=state.lastResult==='correct';gameLayout(`<div class="result minimal-result"><div class="result-icon">${ok?'✓':'✕'}</div>${ok?`<div class="delta">+${q.points}</div>`:''}<button class="btn btn-primary" id="next">التالي</button></div>`);document.getElementById('next').onclick=nextTurn}
function nextTurn(){state.currentTeam++;if(state.currentTeam>=state.teams.length){state.currentTeam=0;state.currentRound++}state.screen=state.currentRound>state.rounds?'final':'spin';render()}
function finalScreen(){const ranking=[...state.teams].sort((a,b)=>b.score-a.score);shell(`<div class="card winner"><div class="confetti">${Array.from({length:34},(_,i)=>`<i style="left:${Math.random()*100}%;top:${-Math.random()*100}px;background:${TEAM_COLORS[i%TEAM_COLORS.length]};animation-delay:${Math.random()*2}s"></i>`).join('')}</div><div class="trophy">🏆</div><h1>${ranking[0].name} فازوا!</h1><h2>${ranking[0].score} نقطة</h2><div class="ranking">${ranking.map((t,i)=>`<div class="rank-row"><span>${['🥇','🥈','🥉'][i]||`${i+1}.`} ${t.name}</span><strong>${t.score}</strong></div>`).join('')}</div><div class="footer-actions"><button class="btn btn-primary" id="again">العبوا مرة ثانية</button><button class="btn btn-soft" id="setupAgain">غيّروا الإعدادات</button></div></div>`);document.getElementById('again').onclick=()=>{state.currentTeam=0;state.currentRound=1;state.usedQuestions=new Set();state.teams.forEach(t=>{t.score=0;t.lifelines={hint:true,fifty:true,time:true,change:true}});state.screen='spin';render()};document.getElementById('setupAgain').onclick=()=>{state.screen='setup';render()}}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
resetTeams();render();